module.exports =
  "Observer, mesurer, analyser et interpréter une activité ou un système à partir de données" : '6'
  "Observer, mesurer, analyser et interpréter une activité ou un système à partir de données" : '7'
  "Modéliser, concevoir un système d'informations, de décision et de production de biens et de services" : '8'
  "Evaluer, prototyper ou simuler un système" : '9'
  "Dimensionner la partie matérielle et/ou logicielle d'un système" : '10'
  "Piloter un système de production et réagir aux dysfonctionnements" : '11'
  "Choisir des outils de production adaptés, les intégrer dans un environnement et les configurer, et mettre en place un système de production ;=" : '12'
  "Élaborer et mettre en oeuvre une stratégie d’achats" : '13'
  "Piloter les approvisionnements en lien avec la politique de planification et de gestion des stocks" : '14'
  "Localiser et affecter les activités de production, de stockage et transport aux différents membres de la chaîne logistique" : '15'
  "Définir et appliquer un plan d’actions dans le cadre d’une démarche qualité et de l'amélioration continue" : '16'
  "Appréhender et évaluer une structure de manière globale, au travers de grilles de lecture socio-économiques" : '17'
  "Faire évoluer les organisations pour répondre à de nouvelles contraintes ou opportunités" : '18'
  "Prendre en compte l'innovation technologique et méthodologique" : '19'
  "Conduire collectivement un projet : organisation, communication, animation, coordination du groupe" : '20'
  "Piloter un projet en s'appuyant sur un plan directeur (planification, élaboration du budget, définition des indicateurs de suivi, réaliser une recette)" : '21'
  "Identifier, analyser et maîtriser les risques inhérents à un projet" : '22'
  "Identifier, formaliser et contractualiser les besoins d’un client, suivre leur évolution et valider leur respect (traçabilité des besoins)" : '23'
  "Identifier les compétences et savoirs critiques d’une organisation et mettre en oeuvre des outils et méthodes pour les pérenniser" : '24'
  "Réaliser une analyse socio-organisationnelle afin de mieux appréhender les effets des changements et d'y adapter ses stratégies" : '25'
  "Mettre en oeuvre une démarche de responsabilité sociétale" : '26'
